@extends('uson')
@section('title','Historial')
@section('main')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Historial</h1>
        <table class="table table-bordered">
            <thead>
            <th>Status</th>
            <th>Fecha</th>
            <th>Intendente</th>
            <th>Actividad</th>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection